title: José Espiño
description: Computer Engineering Sophomore at the University of Hong Kong
show_downloads: false
remote_theme: tuur29/pages-themes-cayman
darkmode:true
color:
  header: "#000"
  gradient_left: "#e53935"
  gradient_right: "#f57c00"
logo_url: ./favicon.ico
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/tuur29/pages-themes-cayman
  zip_title: Whatever
  zip_hide: false
  tar_url: bla.com
  tar_title: LinkedIn
  tar_hide: false
  github_hide: true
